import request from './request'

export const getExhibits = () => request.get('/exhibits')
export const createExhibit = (data: any) => request.post('/exhibits', data)
export const updateExhibit = (id: string, data: any) => request.put(`/exhibits/${id}`, data)
export const deleteExhibit = (id: string) => request.delete(`/exhibits/${id}`)
export const getScenes = (exhibitId: string) => request.get(`/exhibits/${exhibitId}/scenes`)
export const createScene = (exhibitId: string, data: any) => request.post(`/exhibits/${exhibitId}/scenes`, data)
export const updateScene = (id: string, data: any) => request.put(`/scenes/${id}`, data)
export const deleteScene = (id: string) => request.delete(`/scenes/${id}`)
export const getDevices = (sceneId: string) => request.get(`/scenes/${sceneId}/devices`)
export const getExhibitDevices = (exhibitId: string) => request.get(`/exhibits/${exhibitId}/devices`)
export const createExhibitDevice = (exhibitId: string, data: any) => request.post(`/exhibits/${exhibitId}/devices`, data)
export const bindDeviceToScene = (sceneId: string, deviceId: string) => request.post(`/scenes/${sceneId}/devices`, { device_id: deviceId })
export const unbindDeviceFromScene = (sceneId: string, deviceId: string) => request.delete(`/scenes/${sceneId}/devices/${deviceId}`)
export const switchScene = (sceneId: string) => request.post(`/scenes/${sceneId}/switch`)
export const updateDevice = (id: string, data: any) => request.put(`/devices/${id}`, data)
export const deleteDevice = (id: string) => request.delete(`/devices/${id}`)
export const getDeviceStatus = (id: string) => request.get(`/devices/${id}/status`)
